import Script from "next/script";

export default function Head() {
    return (
        <>
            <title>NTCH</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="google-site-verification" content="OKuE_fBtfiUJ2-RdSwuxVU3tceFJOzrsoy98s3BWEBU" />
            <Script
                strategy="lazyOnload"
                src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GA}`}
            />
            <Script id="ga-script" strategy="lazyOnload">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${process.env.GA}', {
                    page_path: window.location.pathname,
                    });
                `}
            </Script>
        </>
    );
}
